### ISSUE TITLE
[question]Version Release Coordination between cloud_firestore and cloud_firestore_odm

### ISSUE THREAD

**Issue by motucraft** [FirebaseExtended/firestoreodm-flutter#1]
I have a question regarding the version release strategy between cloud_firestore and cloud_firestore_odm. Currently, the latest version of cloud_firestore is 4.15.2, while cloud_firestore_odm depends on cloud_firestore 4.14.0. Given that both packages are closely related, I was wondering if their version releases are coordinated in any way. Specifically, when cloud_firestore is updated, should we expect a corresponding update in cloud_firestore_odm to ensure compatibility, or are their releases independent of each other?

https://github.com/firebase/flutterfire/tree/master/packages/cloud_firestore

Thank you for your time and effort in maintaining these packages.

**Comment by motucraft** [comment]
https://github.com/FirebaseExtended/firestoreodm-flutter/issues/7#issuecomment-1976169509

**Comment by rrousselGit** [comment]
Releases are independent
