### ISSUE TITLE
You cannot use '!=' filters more than once still an issue

### ISSUE THREAD

**Issue by urbanmania** [FirebaseExtended/firestoreodm-flutter#13]
## Expected Behavior
I'm expecting to be able to use _whereFieldPath(FieldPath(const ["rolesQuery"]), arrayContains: auth.currentUser!.uid)_

## Actual Behavior
I get an error: _You cannot use '!=' filters more than once._

## Steps to Reproduce the Problem

This project here re-creates the problem - https://github.com/urbanmania/test_project

## Specifications

- Version: cloud_firestore_odm_generator: ^1.0.0-dev.85
- Platform:

**Comment by gmarizy** [comment]
You have to run  `flutter pub run build_runner build --delete-conflicting-outputs` after upgrading cloud_firestore_odm_generator. Generator is responsible for generating .g.dart files, if you don't execute it it's as if you didn't updated the dependency.

**Comment by gmarizy** [comment]
Well, you took time to create a project showcasing the problem for your issue so nobody is going to say you are unprofessional. I forget to run build_runner after a version update half of the time, that's how I knew immediately what to look after cloning your repo ;o)
